# Generated by Django 2.1.15 on 2020-01-31 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChoices',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineChoices',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteChoices',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterChoices',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('isFaculty', models.BooleanField(default=False)),
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DOB', models.DateField()),
                ('MobileNumber', models.CharField(max_length=13)),
                ('Institute', models.CharField(default='NA', max_length=100)),
                ('Course', models.CharField(default='NA', max_length=100)),
                ('Discipline', models.CharField(default='NA', max_length=100)),
                ('Semester', models.CharField(default='NA', max_length=100)),
                ('Verified', models.BooleanField(default=False)),
                ('UID', models.CharField(default=None, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
